-- --------------------------------------------------------
-- Host:                         localhost
-- Server version:               5.7.24 - MySQL Community Server (GPL)
-- Server OS:                    Win64
-- HeidiSQL Version:             10.2.0.5599
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Dumping structure for table morillo.kategori
CREATE TABLE IF NOT EXISTS `kategori` (
  `idkat` smallint(5) NOT NULL AUTO_INCREMENT,
  `nama` varchar(100) NOT NULL,
  `ket` text NOT NULL,
  `gambar` varchar(100) NOT NULL,
  PRIMARY KEY (`idkat`)
) ENGINE=MyISAM AUTO_INCREMENT=60 DEFAULT CHARSET=latin1;

-- Dumping data for table morillo.kategori: 12 rows
/*!40000 ALTER TABLE `kategori` DISABLE KEYS */;
REPLACE INTO `kategori` (`idkat`, `nama`, `ket`, `gambar`) VALUES
	(47, 'Fosroc', '<p>\r\n	Fosroc adalah pemimpin dunia dalam penyampaian Solusi Konstruktif yang disesuaikan untuk hampir semua jenis proyek konstruksi, menggabungkan produk berkualitas tinggi, dukungan teknis pakar, layanan pelanggan dan inovasi.</p>\r\n<p>\r\n	Di ujung tombak teknologi kimia, Fosroc mengkhususkan diri pada sealant, waterproofing, perbaikan beton, grouts dan anchor, campuran beton dan lapisan pipa. Dengan rangkaian produk dan jaringan global yang sangat maju, Fosroc menawarkan solusi berkualitas tinggi untuk hampir semua pekerjaan, berapapun skalanya.</p>\r\n', '170606.141430.jpg'),
	(48, 'Propan', '<p>\r\n	<strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>\r\n', '170606.141406.jpg'),
	(50, 'ITLS', '<div>\r\n	PT. ITLS Indonesia didirikan pada 2009 dan merupakan bagian dari Nan Pao Group, yang berkantor pusat di Taiwan yang mengkhususkan diri dalam pembuatan perekat, pelapis, resin kimia dan produk kimia khusus.&nbsp;</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	PT. ITLS Indonesia adalah produsen lokal bahan kimia bangunan dan konstruksi yang memproduksi berbagai macam produk cementitious termasuk non-shrink grout, ceramic tile adhesive, colour tile grout, skim coat, mortar untuk bata ringan AAC, concrete repair dan water proofing membrane .</div>\r\n<div>\r\n	&nbsp;</div>\r\n', '20170606.141507.jpg'),
	(51, 'Sika', '<div>\r\n	PRODUK BAHAN KIMIA DAN PEREKAT BERKUALITAS TINGGI UNTUK KONSTRUKSI DAN INDUSTRI</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Sika Indonesia merupakan tempat yang sangat baik untuk memenuhi permintaan produk bahan kimia dan bahan perekat berkualitas tinggi untuk konstruksi bangunan dan industri manufaktur.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	PEMAIN DOMINAN DI PASAR KONSTRUKSI INDONESIA</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Pada tahun 1987, PT. Sika Nusa Pratama didirikan untuk meningkatkan taraf pelayanan lokal untuk industri konstruksi Indonesia. Dengan fasilitas produksi lokal di Cileungsi - Bogor, Sika menjadi pemain dominan di pasar konstruksi Indonesia, dengan mengakui pertumbuhan substansial sepanjang tahun 1990 dan masuk pada abad 21.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	MENJADI PT. SIKA INDONESIA</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Pada tahun 2003 kami mengganti nama menjadi PT. Sika Indonesia dan saat ini kami telah mengkonsolidasikan kantor Penjualan dan Administrasi kami di Cileungsi - Bogor.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	KOMITMEN TERHADAP KEUNGGULAN</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Sika Indonesia berkomitmen untuk unggul dalam solusi yang inovatif dan tetap menyesuaikan produk serta sistem untuk kebutuhan para pelanggan dan pengguna. Sika merupakan perusahaan global dan lokal (Glo-kal), yang menempatkan kebutuhan pelanggan lokal pada pusat kegiatan bisnisnya. Produk dan sistem Sika Indonesia didukung dengan paket layanan yang komprehensif, dirancang khusus untuk kebutuhan pasar lokal.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	BERSETIFIKAT ISO 14001:2004, ISO 9001:2000, DAN ISO 9001:2002</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Sika Indonesia merupakan perusahaan kimia konstruksi pertama di Indonesia yang menerima akreditasi ISO 9001:2002. Di tahun 2004, Kami menerima sertifikat versi terbaru dari ISO 9001:2000. Pada November 2005, Kami berhasil menyelesaikan pelaksanaan sistem pengelolaan lingkungan dan menerima sertifikat ISO 14001:2004.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	MENYEDIAKAN PRODUK UNTUK PROYEK PRESTISIUS</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Sika, telah aktif di Indonesia sejak tahun 1960 dengan menyediakan serangkaian produk untuk beragam proyek-proyek prestisius seperti Pabrik Semen Indocement Tunggal Perkasa di Cibinong, Pembangkit Listrik Tenaga Uap Paiton di Probolinggo, Jembatan Balerang di Batam, Pembangkit Listrik Tenaga Air Singkarak di Sumatera, dan banyak lainnya.</div>\r\n<div>\r\n	&nbsp;</div>\r\n', '20170606.141706.jpg'),
	(52, 'Pentens', '<p>\r\n	Pentens authorized Waterproofing Produk Manufaktur &amp; Trading di Surabaya, Jawa Timur, Indonesia - Pentens Waterproofing Material - Pentens Waterproofing Proyek Konstruksi - Aplikasi Waterproof Perumahan&nbsp;</p>\r\n', '170606.141754.jpg'),
	(53, 'Shell', '<p>\r\n	<strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesettin<strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesettin</p>\r\n', '20170606.142314.jpg'),
	(54, 'Lemkra', '<p>\r\n	<strong>Lorem Ipsum</strong> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry&#39;s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesettin</p>\r\n', '20170606.142336.jpg'),
	(55, 'Morillo', '<p style="box-sizing: border-box; font-family: Raleway, Arial, Helvetica, sans-serif; margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: 1.5; vertical-align: baseline; color: rgb(51, 51, 51);">\r\n	Mengikuti standar internasional, MORILLO terus bergerak dalam memahami karakteristik kinerja yang diperlukan untuk memecahkan masalah dalam waterproofing yang berbeda untuk mencapai solusi yang paling efisien dan ekonomis. Sebagai hasil dari itu, MORILLO tidak hanya menyediakan applikasi yang Terbaik namun juga menyediakan produk-product Terbaik sesuai standar internasional.</p>\r\n<p style="box-sizing: border-box; font-family: Raleway, Arial, Helvetica, sans-serif; margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: 1.5; vertical-align: baseline; color: rgb(51, 51, 51);">\r\n	Morillo mempunyai Product-product dengan&nbsp; standar kualitas tertinggi dengan menerapkan &amp; memperoleh ISO 9001-2000, ISO 14001-2004 dan sertifikat OHSAS 18001-1999, tidak hanya itu, tetapi bahan kami telah diuji dan disetujui oleh banyak laboratorium pengujian independen internasional (Saudi Socotec, Al Hosty Stanger, SASO, Kementerian Pekerjaan Umum, MOT, dll).</p>\r\n<p style="box-sizing: border-box; font-family: Raleway, Arial, Helvetica, sans-serif; margin: 0px 0px 20px; padding: 0px; border: 0px; font-variant-numeric: inherit; font-stretch: inherit; font-size: 14px; line-height: 1.5; vertical-align: baseline; color: rgb(51, 51, 51);">\r\n	Morillo Menyediakan berbagai macam produk bitumen untuk waterproofing dan pemeriksaan lembab architectural dan rekayasa infrastruktur, bangunan, tank, atap, pipa, jalan dan jembatan.</p>\r\n', '20170606.142401.jpg'),
	(56, 'Koster', '<p>\r\n	<span style="font-size:14px;">Waterproofing adalah bagian penting dari proses pembangunan. K&Ouml;STER memiliki spesialisasi di bidang waterproofing sejak 1982. Kami menawarkan berbagai macam sistem waterproofing untuk industri konstruksi dari basement hingga atap. Namun, terkadang masalah waterproofing membutuhkan solusi tersendiri. Itulah sebabnya tim teknis kami yang sangat terampil bekerja sama dengan pelanggan kami untuk menganalisis setiap situasi guna mengembangkan solusi yang memenuhi persyaratan individu pelanggan kami.</span></p>\r\n<p>\r\n	<span style="font-size:12px;">Mengapa waterproofing begitu penting? Setiap tahun, sejumlah besar uang diinvestasikan ke dalam proyek infrastruktur, publik, dan bangunan pribadi. Menurut laporan Pemerintah Jerman tentang kerusakan pada struktur bangunan, 80% kerusakan pada akhirnya berkaitan dengan masalah kedap air. Berinvestasi dalam waterproofing berkualitas tinggi tidak hanya melindungi elemen konstruksi dari masuknya air tetapi juga memastikan efisiensi sumber daya, biaya perawatan yang rendah, dan pengembalian investasi yang tinggi dalam jangka panjang.</span></p>\r\n', '20201017.233247.jpg'),
	(57, 'Ravago', '<p>\r\n	Saat ini, grup Ravago mewakili lebih dari 5.900.000 metrik ton penjualan polimer tahunan yang melayani lebih dari 49.000 pelanggan aktif melalui 285 lokasi di lebih dari 55 negara di seluruh dunia. Kompetensi produksi Ravago terdiri dari 45 fasilitas manufaktur dimana 20 pabrik daur ulang dan peracikan di Amerika Utara, Eropa, Asia dan Afrika dengan kapasitas tahunan gabungan lebih dari 725.000 metrik ton; 16 pabrik produksi di Eropa yang menawarkan solusi produk jadi untuk sektor bangunan dan 7 pabrik dan 6 laboratorium aplikasi untuk bisnis Bahan Kimia kami. Ini semua tidak akan mungkin terjadi tanpa bantuan 7.000 karyawannya.</p>\r\n', '20201017.234040.jpg'),
	(58, 'Geco', '<div>\r\n	Setelah lebih dari 50 tahun pengalaman sukses di bidang waterproofing berdasarkan membran dan teknologi bitumen yang dimodifikasi, sekelompok pengusaha Italia, pemimpin di bidang ini, memutuskan untuk bergabung dengan pengalaman dan keterampilan mereka untuk mencapai visi baru, dengan memperkuat keterampilan dan pengetahuan mereka untuk perbarui bidang ini.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	GECO telah dibuat di Verona agar sejalan dengan perubahan dunia baru, dengan menggabungkan hasil penelitian dan pengembangan maju terbaik, diperoleh dengan semangat dan kerja keras dalam dekade terakhir, awalnya di laboratorium mereka dan kemudian dibuktikan melalui lembaga independen eksternal, untuk menawarkan solusi inovatif, sistem dan produk, memberi perhatian besar dan menghormati persyaratan lingkungan baru, kontraktor dan kebutuhan konsumen, yang menjadi hari demi hari lebih mendasar untuk segala jenis investasi dalam industri bangunan.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	GECO adalah hasil dari visi di atas, siap untuk memenuhi segala jenis permintaan di bidang waterproofing, bahwa sistem dan produk tradisional tidak begitu sering dapat menawarkan, karena dunia yang khusus, cepat dan modern yang kita jalani saat ini, penuh dengan minat pada tema baru, seperti penghematan energi, masalah lingkungan, daur ulang produk, tuntutan industri bangunan, tenaga kerja dan insiden biaya bahan bangunan, di samping tren ekonomi baru, yang lebih berhati-hati dan sensitif daripada di masa lalu, mengenai siklus hidup dari setiap produk, dan solusi cepat yang dibutuhkan kehidupan modern kita lebih parah.</div>\r\n<div>\r\n	&nbsp;</div>\r\n<div>\r\n	Hari ini, GECO mampu menawarkan pasar global masa depan, teknologi dan produk baru mereka, untuk generasi baru yang perlu hidup dalam harmoni dengan lingkungan dan membangun masa depan mereka sendiri, dengan bahan yang inovatif dan akibatnya lebih ekonomis dan tahan lama, untuk lebih solusi yang efisien dan cepat.</div>\r\n', '201017.234521.jpg'),
	(59, 'Awazel', '<p>\r\n	Arabian Waterproofing Industries Co. adalah perusahaan saham gabungan Saudi yang tertutup, dibentuk pada tahun 1974, mengakuisisi dua pabrik di Kota Riyadh dan Jeddah dan memiliki kantor pemasaran dan penjualan di Riyadh, Jeddah, Damam, Dubai, Abu-Dhabi, Kuwait, Doha dan Indonesia. Produk Awazel dirancang untuk mengatasi masalah yang terkait dengan air dengan cara yang ekonomis dan mudah diaplikasikan. Awazel adalah perusahaan Saudi asli yang memproduksi produk berbasis bitumen secara lokal. Saat ini, Awazel memproduksi lebih dari seratus lima puluh jenis penggunaan yang berbeda di jalan raya, tangki, jembatan, atap, waterproofing, pemeriksaan lembab dan tangki.</p>\r\n', '20201017.234901.jpg');
/*!40000 ALTER TABLE `kategori` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
